version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocritic
    - gocyclo
    - gosec
    - bodyclose

  settings:
    gocyclo:
      min-complexity: 12

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocritic