package bun_test

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"scal-p/internal/bun"
	"scal-p/internal/pkgmanager"
)

func mkAdapter(t *testing.T, stdout string, exitCode int) *bun.Adapter {
	t.Helper()
	dir := t.TempDir()
	outPath := filepath.Join(dir, "stdout")
	scriptPath := filepath.Join(dir, "mock.sh")

	if err := os.WriteFile(outPath, []byte(stdout), 0o644); err != nil {
		t.Fatal(err)
	}
	script := fmt.Sprintf("#!/bin/sh\ncat '%s'\nexit %d\n", outPath, exitCode)
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}

	a := bun.New()
	a.CommandContext = func(_ context.Context, _ string, _ ...string) *exec.Cmd {
		return exec.CommandContext(context.Background(), scriptPath)
	}
	return a
}

func mkAdapterCheckArgs(t *testing.T, stdout string, exitCode int, checkFn func(name string, args []string)) *bun.Adapter {
	t.Helper()
	dir := t.TempDir()
	outPath := filepath.Join(dir, "stdout")
	scriptPath := filepath.Join(dir, "mock.sh")

	if err := os.WriteFile(outPath, []byte(stdout), 0o644); err != nil {
		t.Fatal(err)
	}
	script := fmt.Sprintf("#!/bin/sh\ncat '%s'\nexit %d\n", outPath, exitCode)
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}

	a := bun.New()
	a.CommandContext = func(_ context.Context, name string, arg ...string) *exec.Cmd {
		checkFn(name, arg)
		return exec.CommandContext(context.Background(), scriptPath)
	}
	return a
}

func TestAdapterImplementsInterface(t *testing.T) {
	var _ pkgmanager.PackageManager = &bun.Adapter{}
}

func TestAdapterName(t *testing.T) {
	a := bun.New()
	if a.Name() != "bun" {
		t.Errorf("expected bun, got %s", a.Name())
	}
}

func TestAdapterLocalPath(t *testing.T) {
	a := bun.New()
	tests := []struct {
		name string
		want string
	}{
		{"lodash", "node_modules/lodash"},
		{"@scope/pkg", "node_modules/@scope/pkg"},
		{"", "node_modules/"},
	}
	for _, tt := range tests {
		got := a.LocalPath(tt.name)
		if got != tt.want {
			t.Errorf("LocalPath(%q) = %q, want %q", tt.name, got, tt.want)
		}
	}
}

func TestGetTree(t *testing.T) {
	t.Run("falls back to CLI when no lockfile", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		a := mkAdapter(t, `[{"name":"my-project","version":"1.0.0","dependencies":{"lodash":{"version":"4.17.21"}}}]`, 0)
		tree, err := a.GetTree(context.Background())
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if tree.Name != "my-project" {
			t.Errorf("expected name=my-project, got %s", tree.Name)
		}
		dep, ok := tree.Dependencies["lodash"]
		if !ok {
			t.Fatal("missing lodash dependency")
		}
		if dep.Version != "4.17.21" {
			t.Errorf("expected 4.17.21, got %s", dep.Version)
		}
	})

	t.Run("fast path parses lockfile directly", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		lockfile := `# THIS IS A BUN LOCKFILE
# Generated by bun v1.1.0

lodash@4.17.21:
  version: 4.17.21
  resolution: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
  integrity: sha512-test123==

is-odd@3.0.1:
  version: 3.0.1
  resolution: "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz"
  integrity: sha512-abc456==
`
		if err := os.WriteFile("bun.lock", []byte(lockfile), 0o644); err != nil {
			t.Fatal(err)
		}

		a := bun.New()
		tree, err := a.GetTree(context.Background())
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(tree.Dependencies) != 2 {
			t.Fatalf("expected 2 deps, got %d", len(tree.Dependencies))
		}

		lodash, ok := tree.Dependencies["lodash"]
		if !ok {
			t.Fatal("missing lodash")
		}
		if lodash.Version != "4.17.21" {
			t.Errorf("expected 4.17.21, got %s", lodash.Version)
		}
	})
}

func TestInstall(t *testing.T) {
	t.Run("success", func(t *testing.T) {
		a := mkAdapter(t, "", 0)
		if err := a.Install(context.Background()); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("sends correct command", func(t *testing.T) {
		a := mkAdapterCheckArgs(t, "", 0,
			func(name string, args []string) {
				if name != "bun" {
					t.Errorf("expected name=bun, got %s", name)
				}
				if len(args) < 1 || args[0] != "install" {
					t.Errorf("expected install subcommand, got %v", args)
				}
			})
		if err := a.Install(context.Background()); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("passes extra args", func(t *testing.T) {
		a := mkAdapterCheckArgs(t, "", 0,
			func(name string, args []string) {
				got := strings.Join(args, " ")
				if !strings.Contains(got, "lodash express") {
					t.Errorf("expected extra args, got %s", got)
				}
			})
		if err := a.Install(context.Background(), "lodash", "express"); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("failure", func(t *testing.T) {
		a := mkAdapter(t, "error message", 1)
		err := a.Install(context.Background())
		if err == nil {
			t.Fatal("expected error")
		}
	})
}

func TestResolve(t *testing.T) {
	t.Run("success with lockfile present", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		a := mkAdapter(t, "", 0)
		if err := os.WriteFile("bun.lock", []byte(""), 0o644); err != nil {
			t.Fatal(err)
		}

		if err := a.Resolve(context.Background()); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("sends correct command", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		a := mkAdapterCheckArgs(t, "", 0,
			func(name string, args []string) {
				if name != "bun" {
					t.Errorf("expected name=bun, got %s", name)
				}
				got := strings.Join(args, " ")
				if !strings.Contains(got, "install --frozen-lockfile") {
					t.Errorf("expected --frozen-lockfile, got %s", got)
				}
			})
		if err := os.WriteFile("bun.lock", []byte(""), 0o644); err != nil {
			t.Fatal(err)
		}
		if err := a.Resolve(context.Background()); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("fails when frozen install errors", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		a := mkAdapter(t, "", 1)
		if err := a.Resolve(context.Background()); err == nil {
			t.Fatal("expected error when frozen install fails")
		}
	})
}

func TestParseLockfile(t *testing.T) {
	t.Run("basic packages", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		lockfile := `# THIS IS A BUN LOCKFILE
# Generated by bun v1.1.0

lodash@4.17.21:
  version: 4.17.21
  resolution: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
  integrity: sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==

is-odd@3.0.1:
  version: 3.0.1
  resolution: "https://registry.npmjs.org/is-odd/-/is-odd-3.0.1.tgz"
  integrity: sha512-9iEO4qS3oGdE7S9C1rf1XhBfFOrpZTYGy4m1b86N5yI4giR1cOIsfbXkG8N4qLGnZgsMziPD8kDS2YwN7HbQA==
`
		if err := os.WriteFile("bun.lock", []byte(lockfile), 0o644); err != nil {
			t.Fatal(err)
		}

		a := bun.New()
		nodes, err := a.ParseLockfile(context.Background())
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(nodes) != 2 {
			t.Fatalf("expected 2 nodes, got %d", len(nodes))
		}

		byName := map[string]pkgmanager.PackageNode{}
		for _, n := range nodes {
			byName[n.Name] = n
		}

		lodash, ok := byName["lodash"]
		if !ok {
			t.Fatal("missing lodash")
		}
		if lodash.Version != "4.17.21" {
			t.Errorf("lodash version: expected 4.17.21, got %s", lodash.Version)
		}
		if lodash.Integrity != "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==" {
			t.Errorf("lodash integrity mismatch")
		}
		if lodash.Depth != 0 {
			t.Errorf("expected depth 0, got %d", lodash.Depth)
		}

		odd, ok := byName["is-odd"]
		if !ok {
			t.Fatal("missing is-odd")
		}
		if odd.Version != "3.0.1" {
			t.Errorf("is-odd version: expected 3.0.1, got %s", odd.Version)
		}
	})

	t.Run("scoped package", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		lockfile := `# THIS IS A BUN LOCKFILE

@babel/code-frame@7.24.7:
  version: 7.24.7
  resolution: "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.24.7.tgz"
  integrity: sha512-BcYH1CVJBO9tvyIZ2jVeXgSIMvGZ2FDRvDdOIVQyuklNKSsx+eppDEBq/g47Ayw+RqNFE+URvOShmf+f/qwAlA==
`
		if err := os.WriteFile("bun.lock", []byte(lockfile), 0o644); err != nil {
			t.Fatal(err)
		}

		a := bun.New()
		nodes, err := a.ParseLockfile(context.Background())
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(nodes) != 1 {
			t.Fatalf("expected 1 node, got %d", len(nodes))
		}
		if nodes[0].Name != "@babel/code-frame" {
			t.Errorf("expected @babel/code-frame, got %s", nodes[0].Name)
		}
		if nodes[0].Version != "7.24.7" {
			t.Errorf("expected 7.24.7, got %s", nodes[0].Version)
		}
	})

	t.Run("file not found", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		a := bun.New()
		_, err := a.ParseLockfile(context.Background())
		if err == nil {
			t.Fatal("expected error when bun.lock does not exist")
		}
	})

	t.Run("empty lockfile", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		if err := os.WriteFile("bun.lock", []byte(""), 0o644); err != nil {
			t.Fatal(err)
		}

		a := bun.New()
		nodes, err := a.ParseLockfile(context.Background())
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(nodes) != 0 {
			t.Errorf("expected 0 nodes, got %d", len(nodes))
		}
	})

	t.Run("deep indentation (monorepo with nested deps)", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		lockfile := `# THIS IS A BUN LOCKFILE
# Generated by bun v1.2.0

@scope/core@1.0.0:
  version: 1.0.0
  resolution: "https://registry.npmjs.org/@scope/core/-/core-1.0.0.tgz"
  integrity: sha512-corehash==
  dependencies:
    @scope/utils@^1.0.0:
      version: 1.0.5
      integrity: sha512-utilshash==
    lodash@^4.17.21:
      version: 4.17.21
      integrity: sha512-lodashhash==
  optionalDependencies:
    @scope/optional@^0.5.0:
      version: 0.5.1
      integrity: sha512-optionalhash==

@scope/utils@1.0.5:
  version: 1.0.5
  resolution: "https://registry.npmjs.org/@scope/utils/-/utils-1.0.5.tgz"
  integrity: sha512-utilshash==

lodash@4.17.21:
  version: 4.17.21
  resolution: "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
  integrity: sha512-lodashhash==
`
		if err := os.WriteFile("bun.lock", []byte(lockfile), 0o644); err != nil {
			t.Fatal(err)
		}

		a := bun.New()
		nodes, err := a.ParseLockfile(context.Background())
		if err != nil {
			t.Fatalf("unexpected error with deep indent: %v", err)
		}
		if len(nodes) != 3 {
			t.Fatalf("expected 3 nodes, got %d", len(nodes))
		}

		byName := map[string]pkgmanager.PackageNode{}
		for _, n := range nodes {
			byName[n.Name] = n
		}

		if _, ok := byName["@scope/core"]; !ok {
			t.Error("missing @scope/core")
		}
		if _, ok := byName["@scope/utils"]; !ok {
			t.Error("missing @scope/utils")
		}
		if _, ok := byName["lodash"]; !ok {
			t.Error("missing lodash")
		}
	})

	t.Run("empty entries only", func(t *testing.T) {
		dir := t.TempDir()
		oldWd, _ := os.Getwd()
		if err := os.Chdir(dir); err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := os.Chdir(oldWd); err != nil {
				t.Error(err)
			}
		}()

		lockfile := `# THIS IS A BUN LOCKFILE

pkg@1.0.0:
  version: 1.0.0
  resolution: "https://registry.npmjs.org/pkg/-/pkg-1.0.0.tgz"
  dependencies:
    dep: 2.0.0
`
		if err := os.WriteFile("bun.lock", []byte(lockfile), 0o644); err != nil {
			t.Fatal(err)
		}

		a := bun.New()
		nodes, err := a.ParseLockfile(context.Background())
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(nodes) != 1 {
			t.Fatalf("expected 1 node, got %d", len(nodes))
		}
		if nodes[0].Name != "pkg" {
			t.Errorf("expected pkg, got %s", nodes[0].Name)
		}
		if nodes[0].Version != "1.0.0" {
			t.Errorf("expected 1.0.0, got %s", nodes[0].Version)
		}
	})
}

func TestRegisterBun(t *testing.T) {
	bun.Register()
	pm, err := pkgmanager.Get("bun")
	if err != nil {
		t.Fatalf("expected bun to be registered: %v", err)
	}
	if pm.Name() != "bun" {
		t.Errorf("expected name=bun, got %s", pm.Name())
	}
}
